### ISSUE TITLE
Not compatible with the latest version of Auth0 module

### ISSUE THREAD

**Issue by cpcadmin** [auth0/jwt-auth-bundle#103]
Can you please get this upgraded to use the Auth0 7.2 module?  We'd really like to be using the new stuff if we can.

**Comment by darthf1** [comment]
ping @jimmyjames

**Comment by cpcadmin** [comment]
My apologies, but this is still a big problem for us, we have written custom code as a work around but it is a horrible methodology, especially knowing it things could change in the future.  Really need this to work with newest version of Auth0 sdk.  Thanks.

**Comment by evansims** [comment]
Hey @cpcadmin! 👋 Sorry for the frustration. That's understandable and I certainly sympathize. We're working our way through our PHP libraries as quickly as we can to bring everything up to date, but support around the release of PHP 8 in our upstream SDK has had most of our attention recently. This library is on our radar and will be receiving an update shortly. In the meantime if you have any contributions you'd like to offer to help bring this up to date sooner, pull requests are most welcome

**Comment by amarlot** [comment]
Good news. We are waiting for this update as well.

**Comment by dsism** [comment]
Any prediction? This is the point that is blocking us to use this bundle .

**Comment by evansims** [comment]
@dsism My apologies but I'm not able to give a timeframe at this time. There's quite a bit of work yet to do to support the PHP SDK dependency upgrade. However, efforts toward that end are also part of the PHP 8 compatibility being tracked in #107; once that is released this issue will also be resolved.

**Comment by evansims** [comment]
Just an update on this, we've merged a PR adding support for PHP SDK 7.6 and it's pending a security review. We'll have a release ready soon!

**Comment by RSalo** [comment]
Hi. I can't use this bundle same:
```
  Problem 1
    - Root composer.json requires auth0/jwt-auth-bundle ^3.4 -> satisfiable by auth0/jwt-auth-bundle[3.4.0].
    - auth0/jwt-auth-bundle 3.4.0 requires auth0/auth0-php ^5.2 -> found auth0/auth0-php[5.2.0, ..., 5.7.0] but it conflicts with your root composer.json require (~7.0).
```

**Comment by evansims** [comment]
4.0.0 is now available with support for the 7.x Auth0 PHP SDK branch.
