### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by olix21** [auth0/jwt-auth-bundle#107]
Hello,

The 8th version of PHP was released last month. It could be great to support it.

I don't know if you guys have any plan to support it or if you rely on the community to do so.
I didn't take time (yet) to investigate what change should be made to ensure the PHP 8 compatibility

**Comment by evansims** [comment]
Hey @olix21 👋 Thanks for bringing this up. Definitely on my radar. I'm presently working on updating [our upstream PHP SDK](https://github.com/auth0/auth0-PHP) to support PHP 8, and after that is released we can migrate that support down to this library. If you'd like to track progress toward that, [the PR for PHP 8 support is here.](https://github.com/auth0/auth0-PHP/pull/467).

**Comment by mvanduijker** [comment]
I noticed that PHP 8 support is merged in the upstream PHP SDK. We would love to have that in the bundle. Would solve https://github.com/auth0/jwt-auth-bundle/issues/103 as well. Is there any timeline we can expect this work to happen or are there ways we could help?

**Comment by evansims** [comment]
Hey @mvanduijker! 👋 I'm not able to offer a timeline at the moment, but I'm working my way through our PHP ecosystem presently to bring everything up to date. I've not yet looked at this library in terms of necessary changes to introduce PHP 8 support and I don't want to make promises or set expectations until I have a better feel for where this one is at.

Now that support has shipped in the PHP SDK I'm working on Laravel's PHP 8 support, followed by WordPress and this library. If you'd like to get started on this before I'm able to though, PRs are most welcome!

**Comment by mvanduijker** [comment]
Thanks for the update @evansims. We are not quite ready to make the move to PHP8 yet. But when this will be the last thing on our list I can try to make some time to make a contribution.

**Comment by evansims** [comment]
Just an update on this, we've merged the PR supporting PHP 8 and it's pending a security review. We'll have a release ready soon!

**Comment by evansims** [comment]
PHP 8.0 support is now available with the 4.0.0 release. 🥳 Thanks again for your help on this, @olix21.
