### ISSUE TITLE
Inconsistent install instructions for master branch

### ISSUE THREAD

**Issue by sufius** [auth0/jwt-auth-bundle#117]
Could you please provide some useful install instructions for the master branch. There is written that you should install this bundle like this:

`composer require auth0/jwt-auth-bundle:"~3.0"`

but the configuration underneath is not fitting to the configuration required for branch ~3.0

also the master branch is not ~3.0, it is ~4.0...

It would be really nice to provide at least one single example demo project which is pointing to the right direction.

Thank you very much

**Comment by evansims** [comment]
Hi @sufius 👋  You're correct, you should use ~4.0 to install. I've updated the README. The instructions laid out in the README are otherwise correct.
