### ISSUE TITLE
 conflict between lcobucci/jwt and auth0/php-jwt

### ISSUE THREAD

**Issue by gaetanbuellet** [auth0/jwt-auth-bundle#118]
According to this issue, https://github.com/auth0/auth0-PHP/issues/507 concerning the conflict between lcobucci/jwt and auth0/php-jwt, the version 8.0 is in beta2. So, are you working on an update of this bundle at short therme or should we do it by ourself ?

**Comment by evansims** [comment]
Hi @gaetanbuellet 👋  Unfortunately, I don't currently have an ETA as to when this library will be getting updated to use the new SDK — sorry about that. We're currently slated to update the Laravel package next, after the SDK has a stable release. You might consider checking out [happyr/auth0-bundle](https://github.com/Happyr/auth0-bundle) in the meantime, which a community bundle using the new beta SDK already.
