### ISSUE TITLE
Link not working. Running sample required, otherwise...

### ISSUE THREAD

**Issue by sufius** [auth0/jwt-auth-bundle#120]
Unfortunately the link to a sample project is not working.

![2021_09_21___16_07_54](https://user-images.githubusercontent.com/1421570/134186395-1d9fc803-1183-46dc-99f4-2ef2153c4c94.png)

Could you please provide a working example (for symfony) with usage of protecting routes **by scopes**?

**Comment by evansims** [comment]
Hi @sufius unfortunately we no longer have up to date QuickStarts available for this library. I'll make a note to remove that deprecated link until we can get something online again. If I can answer any questions for you otherwise about using the library please let me know.
