### ISSUE TITLE
Links to examples in documentation are broken

### ISSUE THREAD

**Issue by Brainshack** [auth0/jwt-auth-bundle#122]
### Describe the problem
In the Readme, the link to "Symfony API Samples" and the link to "example code" lead to a 404 page.

### What was the expected behavior?

Links bringing me to the code samples, which would be important for new users.

### Reproduction
Just click the links on the home page of the repository.

### Environment
- master branch

- **Version of this library used:**
- **Which framework are you using, if applicable:**
- **Other modules/plugins/libraries that might be involved:**
- **Any other relevant information you think would be useful:**

**Comment by evansims** [comment]
Hi @Brainshack 👋 Unfortunately we do not currently have any available quickstart documentation for this library. I'd recommend taking advantage of the [Auth0 Community](https://community.auth0.com/) for guidance.

**Comment by ricbra** [comment]
Shouldn't it be better to remove the dead link from the docs here? I stumbled upon the same and also wanted to raise an issue but then found this one.
