### ISSUE TITLE
Dependencies conflict

### ISSUE THREAD

**Issue by francis-roux-serret** [auth0/jwt-auth-bundle#124]
### Package conflict

We are using V4.0.0 of this package and also using the https://github.com/symfony /
[mercure-bundle](https://github.com/symfony/mercure-bundle)

**auth0/jwt-auth-bundle** uses V7 of **auth0/auth0-php**, which uses a fork of [lcobucci/jwt](https://github.com/lcobucci/jwt) package, with same namespace but added breaking changes.
**mercure** bundle use the original [lcobucci/jwt](https://github.com/lcobucci/jwt) package

see [this issue](https://github.com/auth0/auth0-PHP/issues/596)

### Resolution

There is a simple way to resolve the problem, since **auth0/jwt-auth-bundle** ***V8** address that exact problem. By upgrading your dependencies on **auth0/jwt-auth-bundle** to V8 you will solve it.

**Comment by evansims** [comment]
Hi @francis-roux-serret 👋 Thanks for your report. This is a known issue. The fork of the JWT library was necessary for PHP 8 support, as the upstream author did not want to backport changes necessary to support PHP 8 on the 3.x branch. The fork did not include breaking changes, but was incompatible with other libraries with the same dependency.

We will be upgrading this library to use the underlying Auth0-PHP 8 library to resolve this, but I don't have a firm timeline on that to provide you right now.

**Comment by krizon** [comment]
+1. Also have the same issue here 👋

**Comment by evansims** [comment]
👋 I've pinned this issue for public reference. I'll be closing the ticket for now, as our policy is not to leave tickets open that are not actionable in the short term based on our bandwidth/schedule. However, I assure you this work has been backlogged and is on our radar, our closure of the ticket is not indicative of us dismissing its necessity. We'll update this thread and re-open the ticket when we come back to this work.

**Comment by kudlar** [comment]
> ### Package conflict
> We are using V4.0.0 of this package and also using the https://github.com/symfony / [mercure-bundle](https://github.com/symfony/mercure-bundle)
> 
> **auth0/jwt-auth-bundle** uses V7 of **auth0/auth0-php**, which uses a fork of [lcobucci/jwt](https://github.com/lcobucci/jwt) package, with same namespace but added breaking changes. **mercure** bundle use the original [lcobucci/jwt](https://github.com/lcobucci/jwt) package
> 
> see [this issue](https://github.com/auth0/auth0-PHP/issues/596)
> 
> ### Resolution
> There is a simple way to resolve the problem, since **auth0/jwt-auth-bundle** ***V8** address that exact problem. By upgrading your dependencies on **auth0/jwt-auth-bundle** to V8 you will solve it.

It doesn't work for me, because `JWTAuthBundle` class calls `Auth0\SDK\API\Helpers\ApiClient` in its constructor. But this class was removed in **auth0/auth0-php** v8.0.0. It was there in v7.9.2 though.
