### ISSUE TITLE
Add support for symfony/framework-bundle:^6.0

### ISSUE THREAD

**Issue by mkilmanas** [auth0/jwt-auth-bundle#127]
### Describe the problem you'd like to have solved
We are using this bundle yet we cannot upgrade to Symfony 6.0 because this bundle only supports `symfony/framework-bundle: ^4.4 || ~5.1`.

Likewise, it would not be possible to use this bundle on any new project starting up with Symfony 6 (which is publicly available for over 3 months now)

### Describe the ideal solution
Considering that Symfony 5.4 is supported, upgrading to 6.0 should be only the cleanup of deprecations and update in `composer.json`.
One possible issue could be the Security component and the new Authenticator system, but I see there is an open PR here #121  that solves exactly that problem (it's just a little quite there somehow).

## Alternatives and current work-arounds
N/A

### Additional information, if any
N/A

**Comment by evansims** [comment]
Hey @mkilmanas 👋 Thanks for your contribution! I'll give this a review ASAP.

**Comment by evansims** [comment]
Hi @mkilmanas 👋 Thanks for your contributions. I have merged your changes along with #121 into [the new 5.x-dev branch.](https://github.com/auth0/jwt-auth-bundle/tree/5.x-dev) while development continues on that new major.

**Comment by evansims** [comment]
Hi @mkilmanas 👋 Thanks very much for your contributions! I have merged your changes along with #121 into [the new 5.x-dev branch](https://github.com/auth0/jwt-auth-bundle/tree/5.x-dev) while development continues on that new major.

As discussions about features to be included in the next major have become splintered across a few separate issues, let's consolidate further discussion in this thread: https://github.com/auth0/jwt-auth-bundle/issues/130
