### ISSUE TITLE
Please release a stable version 5

### ISSUE THREAD

**Issue by winkbrace** [auth0/jwt-auth-bundle#142]
Hi, thanks for maintaining this package!

`auth0/php-jwt` has recently been abandoned and triggers an error every time you run composer update. It is part of the last stable version of this bundle.
Could you please release a stable version 5, so we can move away from the abandoned package?

Thanks if you have the time :)

**Comment by evansims** [comment]
Hi @winkbrace 👋 Version 5 is currently in active beta testing, but is expected to have its GA in early January.
