### ISSUE TITLE
PHP version on 5.x branches

### ISSUE THREAD

**Issue by carnau** [auth0/jwt-auth-bundle#143]
### Describe the problem

5.x branches require PHP version `^8.0` but Symfony 6.1 packages require `>=8.1`.

### What was the expected behavior?

Installing a 5.x branch should require PHP `>=8.1`

### Reproduction

`composer require auth0/jwt-auth-bundle:5.0.0-BETA1`

### Environment

PHP 8.0

**Comment by evansims** [comment]
Thanks, @carnau, good catch - I'll get that fixed.
