### ISSUE TITLE
Installation method is incorrect

### ISSUE THREAD

**Issue by tristanbes** [auth0/jwt-auth-bundle#15]
Composer requires that the installation of a library is made via 

`composer require library (version) ` 
https://getcomposer.org/doc/03-cli.md#require

It would be best if you specify that instead of manually adding lines in composer.json

**Comment by glena** [comment]
The reason of how it recommend to install was because adoy oauth didn't have a tagged version with the latest changes (it was easier and safer than changing the min stability setting).

Now that they tag it I am changing the doc.

Thanks
