### ISSUE TITLE
Setting secret_base64_encoded as false causes an exception

### ISSUE THREAD

**Issue by mickadoo** [auth0/jwt-auth-bundle#18]
In the `jwt_auth` configuration block setting `secret_base64_encoded` to false throws a `InvalidConfigurationException` with the message
> The path "jwt_auth.secret_base64_encoded" cannot contain an empty value, but got false.

Since the default is true, this means I can't set `secret_base64_encoded` to be false.

**Comment by glena** [comment]
good catch, I will merge and make the release tomorrow.
Thanks

**Comment by glena** [comment]
And v1.2.6 it is.

Thanks
