### ISSUE TITLE
... but is not mandatory

### ISSUE THREAD

**Issue by 3kynox** [auth0/jwt-auth-bundle#20]
Hello there !

Any example to use this bundle without auth0 use ?

Maybe using FOSUser bundle ?

Thanks !

**Comment by glena** [comment]
No, but setting your own user provider (`a0_user_provider` service) and your own `jwt_auth` config should be enough.

The user provider needs to implement this methods https://github.com/auth0/jwt-auth-bundle/blob/master/src/Security/Auth0Service.php

The only thing left is that it will install the `auth0-php` dependency but it shouldnt bother
