### ISSUE TITLE
Symfony 3.0 Upgrade

### ISSUE THREAD

**Issue by frodosghost** [auth0/jwt-auth-bundle#24]
Yesterday I raised a PR #22, but in using the bundle in Symfony 3 I had to make a few more changes. These changes won't work in the Symfony 2.x branches. This is because of the location of `SimplePreAuthenticatorInterface` in the files directory.

What is the process of requesting a merge in this instance? I was going to create a new PR, but that would break the `1.2` branch from working with Symfony 2.x.

**Comment by glena** [comment]
Hi @frodosghost,

I just pushed a new branch called `2.x.x-dev`.

I really appreciate your contributions, feel free to target the PR to this branch.

Thank you

**Comment by frodosghost** [comment]
Hi @glena,

Not a problem. Raised PR #25 for your review.

**Comment by glena** [comment]
:clap: awesome man, so many thanks.

I will review it later today and release v2.0.0
