### ISSUE TITLE
decode call uses invalid arguments

### ISSUE THREAD

**Issue by mickadoo** [auth0/jwt-auth-bundle#29]
Since [this commit](https://github.com/auth0/auth0-PHP/commit/b2eed3736256fda1d407b1f4bd9c796e68dadc5c#diff-58851c54f52841c79c57f1c5dfff1b76) was merged it looks to me like `Auth0Service::decodeJWT` will pass an invalid argument:

```return Auth0JWT::decode($encToken, $this->client_id, $this->client_secret, $this->secret_base64_encoded);```

but the decode method expects

```public static function decode($jwt, $valid_audiences, $client_secret, array $authorized_iss = [])```

which results in:
`Type error: Argument 4 passed to Auth0\\SDK\\Auth0JWT::decode() must be of the type array, boolean given`

**Comment by mickadoo** [comment]
I could create a pull request for this if you'd like, changing the configuration options to accept an array of authorized_iss and removing the secret_base64_encoded

**Comment by jankramer** [comment]
Ran into the same problem. Any news on this topic?

**Comment by mickadoo** [comment]
@jankramer  It looks like this is [fixed in master](https://github.com/auth0/jwt-auth-bundle/blob/master/src/Security/Auth0Service.php) since April, just needs to be tagged. 

Seems the `Auth0Service` class could also be cleaned up a little, the `$this->secret_base64_encoded` is assigned in the constructor but not actually a property. Also `$oauth_client` is never used.

**Comment by mickadoo** [comment]
I  added a [pull request](https://github.com/auth0/jwt-auth-bundle/pulls) which cleans up the things mentioned in my last comment.

**Comment by glena** [comment]
Thx for the PR. I will check this and try to merge this today.

Sorry for the delay with this issue.

**Comment by glena** [comment]
Released under `2.0.1` let me know how this goes

**Comment by jankramer** [comment]
@glena @mickadoo Thanks, that fixed it :+1:

**Comment by OscarOrSomething** [comment]
I'm still getting this, v3

**Comment by mickadoo** [comment]
@OscarOrSomething can you clarify what you mean by v3? The latest tag is 2.0.2

**Comment by OscarOrSomething** [comment]
"auth0/login": "~3.0" is in my composer.json, Will try making it ~2.0

**Comment by OscarOrSomething** [comment]
Still not working

```
        "auth0/login": "~2.0"
```

`Authorization: Bearer e.....`

```
Route::group(['middleware' => ['web']], function () {
  Route::get('/api/protected', array('middleware' => 'auth0.jwt', function() {
	return "Hello";
  }));
});
```

`Type error: Argument 4 passed to Auth0\SDK\Auth0JWT::decode() must be of the type array, null given, called in /home/oscar/Projects/T4A/t4ashop/vendor/auth0/login/src/Auth0/Login/Auth0Service.php on line 91`

**Comment by OscarOrSomething** [comment]
Just realised this is the wrong repo, I guess I should make an issue at auth0/laravel-auth0 ?

**Comment by OscarOrSomething** [comment]
Sorry, Wrong repository, Solved this by adding authorized_issuers to my config and not using an expired token. Soryr

**Comment by glena** [comment]
So guys, can I close this issue? it is fixed for all of you right?

**Comment by OscarOrSomething** [comment]
Probably, Yeah.

**Comment by glena** [comment]
thx
