### ISSUE TITLE
SimplePreAuthenticatorInterface error

### ISSUE THREAD

**Issue by Amialc** [auth0/jwt-auth-bundle#39]
After i've tried to run project, received this error:
![image](https://cloud.githubusercontent.com/assets/1114365/20438687/2d327e34-adc1-11e6-98cd-f444df9a07c3.png)

**Comment by glena** [comment]
which version of symfony?

**Comment by glena** [comment]
Based on the docs, the namespace and classname is ok http://api.symfony.com/3.1/Symfony/Component/Security/Http/Authentication/SimplePreAuthenticatorInterface.html

**Comment by Amialc** [comment]
@glena i have used example, which [use](https://github.com/auth0/jwt-auth-bundle/blob/master/example/composer.json#L11) `2.6.*`

**Comment by glena** [comment]
I just realized that you changed this line https://github.com/auth0/jwt-auth-bundle/pull/40/files#diff-3176edadd76e9f92102a081604b9441eR15

That could be the reason that it is not working

**Comment by Amialc** [comment]
@glena in symfony 2.* SimplePreAuthenticatorInterface is [located](http://api.symfony.com/2.8/Symfony/Component/Security/Core/Authentication/SimplePreAuthenticatorInterface.html) in Core, not HTTP. So this line is changed to be compatible with symfony 2.*

**Comment by glena** [comment]
`Since version 2.8, to be removed in 3.0. Use the same interface from Security\Http\Authentication instead.`

and https://github.com/auth0/jwt-auth-bundle#important

**Comment by Amialc** [comment]
Then example should be updated to 3.* version of symfony.

**Comment by crmpicco** [comment]
Thanks, swapping out `use Symfony\Component\Security\Core\Authentication\SimplePreAuthenticatorInterface;` for `use Symfony\Component\Security\Http\Authentication\SimplePreAuthenticatorInterface;` is all that's needed for the 2.8 upgrade.
