### ISSUE TITLE
1.2.10 SimplePreAuthenticatorInterface error

### ISSUE THREAD

**Issue by Amialc** [auth0/jwt-auth-bundle#41]
(AUTH-3574)
Latest version of 1.x branch jwt-auth-bundle include SimplePreAuthenticatorInterface from `Http` when it should be loaded from `Core`
![image](https://cloud.githubusercontent.com/assets/1114365/21146752/75519788-c15b-11e6-8046-9046343b003b.png)
Proof:
![image](https://cloud.githubusercontent.com/assets/1114365/21146886/e7cc8912-c15b-11e6-82f7-37ea5338e64f.png)
![image](https://cloud.githubusercontent.com/assets/1114365/21146855/cae2242e-c15b-11e6-8adb-bcfe97dfcd50.png)

**Comment by 1ukaz** [comment]
Yup! Same Issue here ...
Is not at Symfony\Component\Security\Http\Authentication\SimplePreAuthenticatorInterface;
but at:
use Symfony\Component\Security\Core\Authentication\SimplePreAuthenticatorInterface;

Simple Fix

**Comment by 1ukaz** [comment]
Why closing without merging?
Sorry if I am mistaken

**Comment by cocojoe** [comment]
Apologies, miss close.

**Comment by 1ukaz** [comment]
Great! Will you merge it anyway?
Thx!

**Comment by cocojoe** [comment]
So just look at libs, the other PR #44 updates the lib to symfony 2.8 which also fixes this [http://api.symfony.com/2.8 SimplePreAuthenticatorInterface.html](http://api.symfony.com/2.8/Symfony/Component/Security/Core/Authentication/SimplePreAuthenticatorInterface.html) 
`core` is deprecated and `http` should be used.

**Comment by joshcanhelp** [comment]
Assuming this has been taken care of so closing for now (and `master` supports Symfony 3). Please let us know if this is still an issue.
