### ISSUE TITLE
Optional field `secret_base64_encoded` does not work.

### ISSUE THREAD

**Issue by paulinevos** [auth0/jwt-auth-bundle#43]
The optional configuration field `secret_base64_encoded` doesn't work when set to `false`. 

`Auth0JWT::decode` will always attempt to decode the secret, even if it was never base64encoded to begin with, and verifying the signature fails.

**Comment by paulinevos** [comment]
To test:
Set the `client_secret` option to a plain text value instead of a base64encoded value.

**Comment by paulinevos** [comment]
Nvm, should've compared versions...

**Comment by glena** [comment]
@paulinevos you manage to make it work?
