### ISSUE TITLE
client_secret is no longer base64 encoded by default

### ISSUE THREAD

**Issue by leesiongchan** [auth0/jwt-auth-bundle#45]
See https://auth0.com/forum/t/client-secret-stored-without-base64-encoding/4338

So do you think it makes sense to have `secret_base64_encoded` option back?

**Comment by glena** [comment]
Yes but didnt have to work on it yet. Do you depend on this? if so I can try to tackle this week

**Comment by leesiongchan** [comment]
@glena Yea, that would be great!

**Comment by glena** [comment]
ok, sorry about this, I will work on that.

**Comment by glena** [comment]
which version are you using?
also, this change will require you to upgrade to auth0-php v4

**Comment by leesiongchan** [comment]
I am using v2

**Comment by glena** [comment]
Can you give it a try before releasing? https://github.com/auth0/jwt-auth-bundle/pull/46

The tag to be used with composer is `3.0.0-beta.1`.

Remember that you will need to upgrade to auth0-php v4 if you are using this in your project.

**Comment by aequasi** [comment]
3.0.0-beta.1 seems to be broken.

**Comment by petrepatrasc** [comment]
Any updates on this? As @aequasi has mentioned the 3.0.0-beta.1 branch is broken and new customers are unable to use Auth0 due to the December change.

**Comment by glena** [comment]
@aequasi thx and sorry. can you check `3.0.0-beta.2`?

**Comment by zazoomauro** [comment]
+1

**Comment by zazoomauro** [comment]
3.0.0-beta.2 throws

```console
[Symfony\Component\Debug\Exception\ContextErrorException]  
  Notice: Uninitialized string offset: 0
```

**Comment by glena** [comment]
@zazoomauro can you provide more info? a callstack would be helpful

**Comment by zazoomauro** [comment]
Simple latest symfony stable version installed with your bundle on your beta 2 commit

**Comment by glena** [comment]
@zazoomauro Can you provide the full error with a call stack please?

**Comment by zazoomauro** [comment]
I don't know how to do it really...
this just happens when you try to do a simple bin/console or a very small operation.

**Comment by glena** [comment]
@zazoomauro Seems that one of the newer releases of symfony cant parse multiline arrays in yml files.
I just pushed `3.0.0-beta3` with the fix. 
If it works properly, I will release the final `3.0.0`

**Comment by zazoomauro** [comment]
next error: `Attempted to load class \"JWTVerifier\" from namespace \"Auth0\\SDK\".\nDid you forget a \"use\" statement for another namespace?`

Check in your Auth0Service class. 

```php
use Auth0\SDK\JWTVerifier
```

does not exists.

**Comment by glena** [comment]
sorry cant repro.

Please check that the auth0-php sdk is installed and that it is the correct version required by this package `^4.0.11`
