### ISSUE TITLE
Give us a way to specify cache when the JWTVerifier is created

### ISSUE THREAD

**Issue by tchaffee** [auth0/jwt-auth-bundle#50]
The Auth0Service uses JWTVerifier from the [auth0-PHP SDK](https://github.com/auth0/auth0-PHP). auth0-PHP allows specifying a [cache](https://github.com/auth0/auth0-PHP#decoding-and-verifying-tokens) which will greatly speed up requests to the Auth0Service. I am currently experience a 3000 millisecond response time for every request that uses the Auth0Service. I manually changed the Auth0Service to use cache and the response time has gone back down to a reasonable 300 milliseconds.

**Comment by cocojoe** [comment]
@Nyholm you mind if I summon you here? You're the Symfony guy 😄

**Comment by Nyholm** [comment]
Of course. No problems at all.

@tchaffee Please try the patch in #51. That will help you.
