### ISSUE TITLE
Allow multiple audiences in config

### ISSUE THREAD

**Issue by erichard** [auth0/jwt-auth-bundle#54]
I have two clients in auth0 one for a PWA and one for a native apps. Both should communicate with a Symfony API where I use this bundle. 

As I see, the `JWTVerifier` is capable to validate token for mutliple audience but the auth0Service use  only one audience.

**Comment by erichard** [comment]
Hello ?

**Comment by irikanderson** [comment]
This is an annoying limitation.

I have made this work by changing line 145 of Auth0Service to:

            'valid_audiences' => array_merge([ config('laravel-auth0.client_id') ], config('laravel-auth0.api_identifier')),

and then supplying config('laravel-auth0.api_identifier') as an array via the config

Would be nice if this Service was updated to support the complete functionality of JWTVerifier()

**Comment by joshcanhelp** [comment]
@erichard - Apologies for the delay here. We're working on this now for anyone else having this issue and will put out a new release as soon as it is merged. 

@irikanderson - Thank you for posting a work-around here.
