### ISSUE TITLE
Support Symfony4

### ISSUE THREAD

**Issue by novacp** [auth0/jwt-auth-bundle#55]
Are there any plans to support sf4 in the near future? This is like a real blocker (for me) to use Auth0 in the future.

**Comment by avramcosmin** [comment]
Same here. Already looking to an alternative to Auth0. Will cost us less build or move to another authentication service than maintaining a Symfony 3 application.

**Comment by n3vrax** [comment]
why is this so hard?...there is already a pull request for this

**Comment by joshcanhelp** [comment]
Apologies for the delay everyone. I'll get this into our board and in an upcoming sprint. 

@n3vrax - #56 just adjusts Composer to allow Symphony 4.0, we haven't tested the rest of the code to make sure it all works. If you have and confirm that no other changes need to be made, that would be helpful to know.

**Comment by n3vrax** [comment]
I forked and changed composer.json as in the pull request. I successfully installed the package, and symfony flex also enabled the bundle automatically. Other than that, I think the package can be used without any change. I'm still working on integrating it in my application, but haven't seen any issues with the code so far.

**Comment by joshcanhelp** [comment]
Thank you @n3vrax. Hopefully the update will require minimal changes. Again, I'll make sure this is in an upcoming sprint.

**Comment by nightio** [comment]
up

**Comment by joshcanhelp** [comment]
@nightio - Working on it right now :)

My main hesitation with just pushing through #56 is putting our documentation out of date. That said, it's working so far with only minimal updates needed. On track to approve today or Monday 👍 

Thanks for your patience!

**Comment by joshcanhelp** [comment]
🎉
