### ISSUE TITLE
Allow to change the url jwks.json.

### ISSUE THREAD

**Issue by waldo2188** [auth0/jwt-auth-bundle#59]
I use your bundle against our own JWT provider.

In the bundle, the url for retrieving the jwks is hard coded with the value `.well-known/jwks.json`
But the url for retrieving jwks on our provider is `/.well-known/openid-configuration/jwks`.

How can I configure this value with what I need?

**Comment by joshcanhelp** [comment]
@waldo2188 - Thanks for the report here. That's actually hard-coded into the [PHP SDK](https://github.com/auth0/auth0-PHP/blob/eafcf1a24fbf3d49412044008b752be252600e06/src/Helpers/JWKFetcher.php#L67), which this bundle relies on. I'm not seeing any way to configure that at all currently but I will add that as an issue in the SDK and see if we can find a fix here. 

If you have control over the JWKS URL, can you add a redirect from `.well-known/jwks.json` to `.well-known/openid-configuration/jwks`?

**Comment by waldo2188** [comment]
That's my problem, I can't change or add a redirect to this URL. So for now, I have change the URL directly in the PHP SDK. I know it's not a good things to do, but it works. 

Thanks for your reply.
