### ISSUE TITLE
500 on expired token

### ISSUE THREAD

**Issue by Avariya** [auth0/jwt-auth-bundle#63]
`JWT::decode` can throw `ExpiredException`, but any exception is converted to `CoreException` at `JWTVerifier->verifyAndDecode`.
So `CoreException` is throwed to `Auth0Service->decodeJWT` and it is not catched anywhere, what means 500 for Users Application.

To fix it - we need to create internal `ExpiredException` and use it for expired token and transform it to `AuthenticationException`, catch it with built-in `AuthenticationFailureHandlerInterface` and throw 401 code according to https://stackoverflow.com/questions/8855297/token-expired-json-rest-api-error-code

Full stack trace:
![image](https://user-images.githubusercontent.com/13464158/49290718-60304e00-f4b0-11e8-9e1e-f888ce768f1b.png)

**Comment by Avariya** [comment]
So fine fix will include pull requests to `auth0/auth0-php` and `auth0/jwt-auth-bundle` repositories. Are you ok with it? I can propose PR if this solution looks good for maintainers.

**Comment by joshcanhelp** [comment]
@Avariya - thank you for the report here! I don't think I totally follow though ... The `\Auth0\SDK\JWTVerifier::verifyAndDecode` method throws a number of exceptions, it's meant to be used in a `try...catch` block. By proxy, the calling method should be wrapped as well. They are converted to `CoreException` so you don't have to also be aware of all the different exceptions that can be thrown by the JWT library we're using. The exceptions bubbling up is intensional. 

Am I missing something?

**Comment by joshcanhelp** [comment]
I agree, it's not ideal in this case but changing that would be a breaking change for that SDK (issue should actually be raised there) because we'd be passing new Exception types. I'll make a note of it internally for a major version change. You can use the error message to output or log the issue, if needed.
