### ISSUE TITLE
Remove SimplePreAuthenticatorInterface?

### ISSUE THREAD

**Issue by darthf1** [auth0/jwt-auth-bundle#80]
Thanks for merging https://github.com/auth0/jwt-auth-bundle/pull/75!

Looking at the logs, I still get the following deprecation message:

`The "Auth0\JWTAuthBundle\Security\JWTAuthenticator" class implements "Symfony\Component\Security\Http\Authentication\SimplePreAuthenticatorInterface" that is deprecated since Symfony 4.2, use Guard instead.`

Since `Guard` is supported since SF 2.8, and the current latest [supported ](https://symfony.com/roadmap) release is 3.4.31, is it possible to remove the SimplePreAuth implementation alltogether?

**Comment by joshcanhelp** [comment]
@darthf1 - Is that something you can do in your app or does it have to be removed from the library itself? 

I'm fine with deprecating it now but it will need to be a major release to remove it completely.

**Comment by darthf1** [comment]
I think this can be closed as i have no issues with SF 5.0

**Comment by gigo6000** [comment]
@darthf1 could you please share your solution? the `JWTAuthenticator` provided by the bundle is not supported by Symfony 5 because of this `SimplePreAuthenticatorInterface`. I'm trying to implement this bundle on a Symfony 5 project because the `composer.json` allows it but I think is not really ready for that version.

**Comment by darthf1** [comment]
@gigo6000 I have `"auth0/jwt-auth-bundle": "3.3.1",` in my `composer.json` without any issues related to the SimplePreAuthenticatorInterface.

**Comment by gigo6000** [comment]
@darthf1 that's weird, I guess you're using a different authenticator, could you share your `security.yml` firewall config?

**Comment by gigo6000** [comment]
I realize there's actually a guard authenticator included in the bundle: https://github.com/auth0/jwt-auth-bundle/blob/master/src/Security/Guard/JwtGuardAuthenticator.php, and the service id is `jwt_auth.security.guard.jwt_guard_authenticator`, so the `jwt_auth.jwt_authenticator` should only be used for older Symfony versions.

**Comment by obukhov** [comment]
@gigo6000 thanks so much for your message. I wish that would be written in the doc for this package (which is missing)
