### ISSUE TITLE
Broken link to Symfony API QuickStart Guide, is this bundle still maintained?

### ISSUE THREAD

**Issue by dunglas** [auth0/jwt-auth-bundle#91]
### Description

The link to the `Symfony API QuickStart Guide` is broken.
This guide doesn't seem to exist anymore on the website.

Is this intended? Is it still a good idea to use this bundle to integrate Auth0 in a Symfony app?

**Comment by niels-nijens** [comment]
Hey @dunglas, we're still successfully using this bundle in our Symfony 4 projects.

It seems Auth0 updated their documentation pages and forgot about the Symfony integration... (Or a new/updated quickstart is not done yet?)

**Comment by dunglas** [comment]
Thanks for the feedback @niels-nijens!

**Comment by dunglas** [comment]
I confirm that this bundle still works on my app too. However it relies on a deprecated version of the Auth0 PHP SDK.

**Comment by darthf1** [comment]
@joshcanhelp could you bring the situation to light? :) I see there's a few PR's open for a while now and the bundle is using an old version of the SDK.

**Comment by darthf1** [comment]
ping @lbalmaceda @joshcanhelp

**Comment by dunglas** [comment]
This still is an issue.

**Comment by jimmyjames** [comment]
Thanks for raising this issue. 👍 

That Quickstart was removed as part of an effort to streamline our guidance across the wide tech stack landscape. We'll update the `README`  to remove that broken link, but keep the link to the samples repository.

Regarding your question about if this library is still recommended and maintained, I'll be as transparent as possible:

- We are currently looking to hire someone with PHP expertise (and other technologies) to fill a gap on our team. If you or anyone else is interested in joining a great team and company, [check it out](https://auth0.com/careers/job/developer-experience-engineer-sdk:e2ac10c8-ca82-431f-ad3c-c118ee2def5f)!
- As discussed in the comments above, this bundle does still work, though it does use an old version of `auth0-PHP`. Updating it to the latest version will likely have to wait until we fill that role and determine the long-term plan of this SDK (more on this next).
- Longer term, we may look to transition this library from an official Auth0 library to a community-maintained library (if there is interest), similar to the [Symfony Samples](https://github.com/auth0-community/auth0-symfony-api-samples). If you or anyone else has any interest in being a maintainer, let us know!

Hope that info helps, though I acknowledge there's not cut-and-dry answers to your questions at this time. I'll follow-up with a PR to remove the broken link. Thanks!

**Comment by jimmyjames** [comment]
We've removed the broken link with #102. I'm going to close this issue, but feel free to raise any questions here, and we'll do our best to answer any additional questions.
